[package]
name = "shahmaat"
description = "Online multiplayer chess game"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full", "macros"] }
tokio-tungstenite = "0.26"
futures-util = "0.3"
env_logger = "0.11"
anyhow = "1.0"
http = "1.2"
log = "0.4"
